### ISSUE TITLE
Civitai Model download fails for models with dynamic pictures

### ISSUE THREAD

**Issue by gafter** [alexandersokol/sd-model-organizer#77]
If a model has an animated picture, downloading the model using "Import Civitai URL" fails.

Example of a model that won't download:
- https://civitai.com/models/218591/happy-sliders-ntcaixyz?modelVersionId=305221

The download manager saves an error message in a file whose name is a two or three-digit integer, and thinks it succeeded in downloading the model.

**Comment by OuterNeptunium** [comment]
I'm also getting a similar issue (where Model Organizer saves an integer-named file). However, it turns out (at least in my case) that the file is actually a HTML file. I added the `.html` extension and opened it, and was presented with a copy of CivitAI's page saying the model author requires users to be logged in to view the model.

Correct me if I'm wrong, but I think that API keys are going to be needed now.

**Comment by joelyoder** [comment]
Just tested out the new version of the plugin with an API key configured. Weirdly enough, it still will download two files with an ID for a name sometimes, but the file without an extension is the full safetensors file.

**Comment by joelyoder** [comment]
FYI @alexandersokol testing this last release, I don't think this issue is fully fixed. It isn't having trouble getting the files anymore, but it's still struggling to pull the correct filenames sometimes.

**Comment by alexandersokol** [comment]
Hello!
I tested with it several models, but everything looks good with both downloading and file names.
Please create a new issue if you will be able to reproduce it again and add links to the models.

**Comment by joelyoder** [comment]
Will do! I think I should be able to recreate it pretty easily if it's still an issue.
